# Generated by Django 5.1.3 on 2024-12-01 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comandas', '0034_comensales_token_alter_pedidos_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comensal', 'Acceso de Comensal'), ('atencion', 'Solicitud de Atención')], max_length=20)),
                ('estado', models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Aprobado'), (2, 'Rechazado')], default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comandas.mesa')),
            ],
        ),
    ]
