# Generated by Django 5.1.2 on 2024-10-27 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comandas.categorias')),
            ],
        ),
    ]
