# Generated by Django 5.1.2 on 2024-10-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0003_categorias_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='descripcion',
            field=models.TextField(default=1.0),
            preserve_default=False,
        ),
    ]
