# Generated by Django 5.1.2 on 2024-10-28 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0007_user_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rol',
        ),
    ]
