# Generated by Django 5.1.2 on 2024-10-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0008_remove_mesa_estado_remove_user_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='estado',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
