# Generated by Django 5.1.2 on 2024-10-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0009_mesa_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
