# Generated by Django 5.1.2 on 2024-10-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0011_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='imagen',
            field=models.ImageField(null=True, upload_to='categorias'),
        ),
    ]
