# Generated by Django 5.1.2 on 2024-11-03 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0013_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesa',
            old_name='estado',
            new_name='activa',
        ),
    ]
