# Generated by Django 5.1.2 on 2024-11-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0014_rename_estado_mesa_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='capacidad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Libre'), (1, 'Ocupado')], null=True),
        ),
        migrations.AddField(
            model_name='mesa',
            name='ubicacion',
            field=models.IntegerField(choices=[(0, '1er piso'), (1, '2er piso'), (2, '3er piso'), (3, 'terraza')], null=True),
        ),
    ]
