# Generated by Django 5.1.2 on 2024-11-09 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0015_mesa_capacidad_mesa_estado_mesa_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comandas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('sub_total', models.IntegerField(null=True)),
                ('propina', models.IntegerField(null=True)),
                ('descuento', models.IntegerField(null=True)),
                ('total', models.IntegerField(null=True)),
                ('estado', models.IntegerField(choices=[(0, 'Abierta'), (1, 'Cerrada')])),
                ('notas', models.TextField(null=True)),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
