# Generated by Django 5.1.2 on 2024-11-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0016_comandas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comandas',
            name='descuento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comandas',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comandas',
            name='propina',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comandas',
            name='sub_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comandas',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
