# Generated by Django 5.1.2 on 2024-11-11 23:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0017_alter_comandas_descuento_alter_comandas_notas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comandas',
            old_name='fecha',
            new_name='fecha_ini',
        ),
        migrations.RemoveField(
            model_name='comandas',
            name='hora',
        ),
        migrations.AddField(
            model_name='comandas',
            name='abono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comandas',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comandas',
            name='iva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comandas',
            name='medio_pago',
            field=models.IntegerField(choices=[(0, 'Efectivo'), (1, 'Transferencia'), (2, 'Tarjetas')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comandas',
            name='mesa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='comandas.mesa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comandas',
            name='valor_neto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
