# Generated by Django 5.1.2 on 2024-11-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0019_alter_comandas_medio_pago_alter_comandas_mesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comandas',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comandas',
            name='fecha_ini',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
