# Generated by Django 5.1.2 on 2024-11-12 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0022_comensales_alter_sucursal_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('total_pedido', models.IntegerField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, choices=[(0, 'preparacion'), (1, 'entregado'), (2, 'pendiente')], null=True)),
                ('comanda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comandas.comandas')),
                ('comensal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comandas.comensales')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comandas.producto')),
            ],
        ),
    ]
