# Generated by Django 5.1.3 on 2024-11-17 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0023_pedidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='comanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='comandas.comandas'),
        ),
    ]
