# Generated by Django 5.1.3 on 2024-11-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0024_alter_pedidos_comanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='Ptiempo',
            field=models.IntegerField(blank=True, choices=[(0, 5), (1, 10), (2, 15), (3, 20), (4, 25), (5, 30), (6, 35), (7, 40), (8, 45), (9, 50), (10, 55), (11, 60)], null=True),
        ),
    ]
