# Generated by Django 5.1.3 on 2024-11-17 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0025_pedidos_notas_producto_ptiempo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Ptiempo',
            new_name='tiempo',
        ),
    ]
