# Generated by Django 5.1.3 on 2024-11-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0027_pedidos_hora_ini_alter_producto_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='hora_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
