# Generated by Django 5.1.3 on 2024-11-22 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0027_alter_comandas_mesa_alter_comandas_mesero'),
    ]

    operations = [
        migrations.AddField(
            model_name='comensales',
            name='comanda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comandas.comandas'),
        ),
    ]
