# Generated by Django 5.1.3 on 2024-11-23 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0028_comensales_comanda'),
        ('comandas', '0032_alter_pedidos_estado'),
    ]

    operations = [
    ]
